# Generated by Django 2.1.4 on 2019-08-07 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='summary',
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_body',
            field=models.CharField(default='Add Blog Description Here', max_length=557),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='exit', upload_to='blog_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
