# Generated by Django 2.1.4 on 2019-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190807_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(default='Add Blog Description Here', max_length=557),
        ),
    ]
