# Generated by Django 2.1.4 on 2019-08-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190807_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-title'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
