# Generated by Django 2.1.4 on 2019-08-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190807_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-pub_date'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
